language: python
python:
  - "3.6"
before-install:
  - python --version 
install:
  - pip install -r requirements.txt
script:
  - pytest --cov=./
after-success:
  - bash <(curl -s https://codecov.io/bash)